version: 2
ethernets:
  id0:
    match:
      macaddress: "${mac_address}"
    set-name: enp1s0
    dhcp4: no
    addresses:
      - "${ip_address}"
    gateway4: 192.168.10.1
    nameservers:
      addresses: [8.8.8.8, 8.8.4.4]
